/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jins' at '17. 2. 1 오후 10:42' with Gradle 2.4
 *
 * @author jins, @date 17. 2. 1 오후 10:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
